<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Version>0.0.4</Version>
		<Authors>Akpaev E.A.</Authors>
		<Copyright>Akpaev E.A.</Copyright>
		<PackageProjectUrl>https://github.com/akpaevj/VkWorkspace</PackageProjectUrl>
		<RepositoryUrl>https://github.com/akpaevj/VkWorkspace</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MimeTypes" Version="2.5.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
